export const ICON_NAMES = [
  'telegram',
  'unlockDatabase',
  'unlockLock',
  'unlockWallet',
  'verificationBank',
  'verificationShield',
  'verificationUser',
  'verificationScanner',
  'transferBank',
  'transferCheck',
  'transferLogo',
  'transferClock',
  'transferError',
  'transferInfo',
  'certificateShield',
  'certificateClose',
  'certificateZoom',
  'certificateLock',
  'chatClose',
  'chatAttachment',
  'chatSend',
  'certificateProgressShield',
  'certificateProgressActive',
  'documentFile',
  'documentCard',
  'close',
  'info',
  'eye',
  'burger',
  'back',
  'next',
  'bank',
  'locked',
  'bell',
  'mobileCheck',
  'mobileUpload',
  'mobilePen',
  'mobileCopy',
  'mobileShield',
  'mobileChevron',
  'mobileSimulation',
  'mobileCheckSmall',
  'mobileApproved',
  'mobileAccount',
  'mobileUploadLarge',
  'mobileArrow',
  'mobilePenLarge',
  'mobileArrowMuted',
  'check',
  'upload',
  'pen',
  'arrowLeft',
  'paymentCard',
  'home',
  'documents',
  'profile',
  'chat',
  'copy',
  'shield',
  'chevron',
  'simulation',
  'checkSmall',
  'approved',
  'account',
  'uploadLarge',
  'arrow',
  'penLarge',
  'arrowMuted',
  'logoFull',
  'mobileLogoFull',
] as const;
export type IconName = (typeof ICON_NAMES)[number];
export interface IconProps {
  name: IconName;
  decorative?: boolean;
  ariaLabel?: string;
  title?: string;
}
